name: Gobsman
rules:
  - when:
      red: 0
      green: 0
      blue: 0
      black: 0
    image: template.png
    text: null
  - when:
      red: 0
      green: 0
      blue: 1
      black: 0
    image: pacman.png
    text: null
  - when:
      red: 0
      green: 0
      blue: 0
      black: 1
    image: coco.png
    text: null
  - when:
      red: 2
      green: 0
      blue: 0
      black: 0
    image: cherry.png
    text: null
  - when:
      red: 0
      green: 5
      blue: 0
      black: 0
    image: phantom.png
    text: null
  - when:
      red: 2
      green: 0
      blue: 0
      black: 1
    image: cherryNcoco.png
    text: null
  - when:
      red: 0
      green: 5
      blue: 2
      black: 0
    image: gobsmanDead2.png
    text: null
  - when:
      red: 0
      green: 0
      blue: 1
      black: 1
    image: pacmanCome.png
    text: null
  - when:
      red: 2
      green: 0
      blue: 1
      black: 1
    image: pacmanComecherryyCoco.png
    text: null
  - when:
      red: 2
      green: 0
      blue: 1
      black: 0
    image: pacmancomecherry.png
    text: null
  - when:
      red: 0
      green: 5
      blue: 1
      black: 0
    image: phantompacman.png
    text: null
